# Generated by Django 4.0.6 on 2022-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_had_done',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects_had_not_done',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
