# Generated by Django 4.0.6 on 2022-07-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0003_projects_had_done_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_done_no', models.IntegerField(default=0)),
                ('users_world_no', models.IntegerField(default=0)),
                ('avilable_countries_no', models.IntegerField(default=0)),
                ('award_winners_no', models.IntegerField(default=0)),
            ],
        ),
    ]
