# Generated by Django 4.0.6 on 2022-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0005_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='define_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
