# Generated by Django 4.0.6 on 2022-07-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0007_projects_had_not_done_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_had_done',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
