# Generated by Django 4.0.6 on 2022-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0010_pranches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='work_steps/')),
            ],
        ),
    ]
