# Generated by Django 4.0.6 on 2022-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0011_work_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_bg_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_img1', models.ImageField(blank=True, upload_to='site_bg_images/')),
                ('home_page_img2', models.ImageField(blank=True, upload_to='site_bg_images/')),
                ('bar_img', models.ImageField(blank=True, upload_to='site_bg_images/')),
            ],
        ),
    ]
