# Generated by Django 4.0.6 on 2022-07-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARTUP', '0012_site_bg_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
